### ISSUE TITLE
请问这个比赛数据可以分享一下吗？

### ISSUE THREAD

**Issue by cxy229** [YingZiqiang/LES-MMRC-Summary#1]
请问这个比赛数据可以分享一下吗？想要复现一下代码，进行学习。谢谢。

**Comment by YingZiqiang** [comment]
数据有点大，我压缩了放百度网盘了，大约200多M。
链接: https://pan.baidu.com/s/1abjlYNkiAtI21RHL2y9T4A  密码: wk59

**Comment by YingZiqiang** [comment]
@cxy229 数据有点大，我压缩了放百度网盘了，大约200多M。
链接: https://pan.baidu.com/s/1abjlYNkiAtI21RHL2y9T4A 密码: wk59

**Comment by cxy229** [comment]
万分感谢
