### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by MaChenjia** [YingZiqiang/LES-MMRC-Summary#2]
您好，比赛已经结束无法下载训练集，可以麻烦您分享一下训练集吗？非常感谢！
我的邮箱是missmcj0704@gmail.com

**Comment by Tresfroid** [comment]
您好，我也很需要这份数据集，请问可以分享一下吗？
邮箱：lj931727642@163.com

**Comment by Tresfroid** [comment]
您好，我也很需要这份数据集，请问可以分享一下吗？
邮箱：lj931727642@163.com

**Comment by YingZiqiang** [comment]
@MaChenjia @Tresfroid 这个数据集我分享过~
https://github.com/YingZiqiang/LES-MMRC-Summary/issues/1

**Comment by Tresfroid** [comment]
好的谢谢～
